# Generated by Django 5.2 on 2025-04-22 08:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('line_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shift_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('line_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_products', to='core.line')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_products', to='core.product')),
            ],
            options={
                'unique_together': {('line_id', 'product_id')},
            },
        ),
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('line_speed', models.FloatField()),
                ('total_production', models.IntegerField()),
                ('total_energy_consumed', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_data', to='core.line')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_data', to='core.product')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_data', to='core.shift')),
            ],
            options={
                'unique_together': {('line', 'product', 'shift', 'date')},
            },
        ),
    ]
